version: '3.5'

services:
  mysql:
    image: mysql:5.7
    container_name: sap_painel_mysql
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    tty: true
    restart: always
    
  php:
    image: php:7.2.9-fpm-alpine
    container_name: sap_painel_php
    ports:
      - 9000
    volumes:
      - ./fonte:/var/www/html
    links:
      - mysql
    depends_on:
      - mysql
    tty: true
    restart: always

  nginx:
    image: nginx:1.15.2-alpine
    container_name: sap_painel_nginx
    ports:
      - 80:80
    volumes:
      - ./fonte:/var/www/html
      - ./docker:/etc/nginx/conf.d
    links:
      - php
    depends_on:
      - php
    tty: true
    restart: always

volumes:
  mysql_data:
    name: mysql_data
